config/routes.rb
Rails.application.routes.draw do
  get '/splash', to: 'splash#index'

  devise_for :users

  devise_scope :user do
    authenticated :user do
      root 'groups#index', as: :authenticated_root
    end

    unauthenticated do
      root "splash#index", as: :unauthenticated_root
    end
  end

  resources :users, only: [:index, :show, :new] do
    resources :groups, only: [:new, :create, :show, :index, :destroy]
    resources :expenses, only: [:new, :create, :index, :show, :destroy]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/expense.rb
class Expense < ApplicationRecord
  has_and_belongs_to_many :groups, join_table: :join_group_and_expenses
  belongs_to :author, class_name: 'User'

  validates :name, presence: true, length: { minimum: 3, maximum: 50 }
  validates :amount, presence: true, numericality: { greater_than: 0 }
end

app/models/group.rb
class Group < ApplicationRecord
  has_and_belongs_to_many :expenses, join_table: :join_group_and_expenses
  belongs_to :author, class_name: 'User'

  validates :name, presence: true, length: { minimum: 3, maximum: 50 }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :expenses, dependent: :destroy
  has_many :groups, foreign_key: :author_id

  validates :name, presence: true, length: { minimum: 3, maximum: 50 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: %i[name email password])
    devise_parameter_sanitizer.permit(:account_update, keys: %i[name email password current_password])
  end
end

app/controllers/expenses_controller.rb
class ExpensesController < ApplicationController
  def new
    @expense = Expense.new
    @groups = current_user.groups
    @user = current_user
  end

  def create
    @expense = Expense.new(expense_params)
    if @expense.save
      redirect_to user_group_path(@expense.author_id, @expense.group_ids), notice: 'Expense created successfully.'
    else
      @groups = current_user.groups
      render :new
    end
  end

  private

  def expense_params
    params.require(:expense).permit(:name, :amount, group_ids: []).merge(author: current_user)
  end
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_group, only: [:show]

  def index
    @groups = Group.order(created_at: :desc).all
    @user = current_user
  end

  def show; end

  def new
    @group = current_user.groups.build
  end

  def create
    @group = current_user.groups.build(group_params)
    if @group.save
      redirect_to authenticated_root_path, notice: 'Group was successfully created.'
    else
      render :new
    end
  end

  private

  def set_group
    @group = Group.find(params[:id])
  end

  def group_params
    params.require(:group).permit(:name, :icon)
  end
end

app/controllers/splash_controller.rb
class SplashController < ApplicationController
  def index
    render 'splash'
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/expenses/new.html.erb
<div class="categories-header">

  <%= render "shared/mobile_menu" %>

  <div> NEW TRANSACTION</div>

  <%= link_to authenticated_root_path do %>
    <i class="material-icons">search</i>
  <% end %>
</div>

<div>
  <%= form_with(model: @expense, url: user_expenses_path, local: true) do |form| %>
    <% if @expense.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(@expense.errors.count, "error") %> prohibited this expense from being saved:</h2>
        <ul>
          <% @expense.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
        </ul>
      </div>
    <% end %>

    <div class="field">
      <%= form.text_field :name, autofocus: true,  placeholder: "Enter Name"  %>
    </div>

    <div class="field">
      <%= form.text_field :amount,   placeholder: "Enter Amount"  %>
    </div>

    <div class="field-select">
      <%= form.label :group_ids, "Select Atleast One Category:", class: "atleast" %>
      <%= form.select :group_ids, options_from_collection_for_select(@groups, :id, :name), {}, { multiple: true, class: "form-select" } %>
    </div>

    <div class="actions">
      <%= form.submit "Save", class: "create-category save-category" %>
    </div>

  <% end %>
</div>

<div class="go-back-button"><%= link_to "Back", :back %></div>

app/views/groups/index.html.erb
<div class="categories-header">
  <%= render "shared/mobile_menu" %>
  <div>CATEGORY</div>
  <%= link_to authenticated_root_path do %>
    <i class="material-icons">search</i>
  <% end %>
</div>

<div class="most-recent">
  <p>Most recent</p>
  <h3>.</h3>
</div>

<div class="cate-container">
  <% if @groups.empty? %>
    <p style="color: green; font-size: 20px; text-align: center;">No Categories Added Yet.</p>
  <% else %>
    <% @groups.each do |group| %>
      <% if current_user.id == group.author_id %>
        <%= link_to user_group_path(group.author, group) do %>
          <div class="cate">
            <div><%= image_tag group.icon %></div>
            <div class="cate-data-container">
              <p class="cate-name"> <%= group.name %> </p>
              <p class="cate-time"> <%= group.created_at.strftime("%d %b %Y") %> </p>
            </div>
            <div> <p class="cate-amount"> $<%= group.expenses.sum(:amount) %> </p></div>
          </div>
        <% end %>
      <% end %>
    <% end %>
  <% end %>
</div>

<div class="create-new-category"><%= link_to "Add New Category", new_user_group_path(@user) %></div>

app/views/groups/new.html.erb
<div class="categories-header">

  <%= render "shared/mobile_menu" %>

  <div> NEW CATEGORY</div>

  <%= link_to authenticated_root_path do %>
    <i class="material-icons">search</i>
  <% end %>
</div>

<div>
  <%= form_with model: @group, url: user_groups_path do |form| %>
    <div class="field">
      <%= form.text_field :name,   placeholder: "Enter Name" %>
    </div>

    <div class="field">
      <%= form.text_field :icon, placeholder: "Icon link" %>
    </div>

    <%= form.submit "Create Category", class: "create-category" %>
  <% end %>
</div>

<div class="create-new-category"><%= link_to "Back to Categories",  authenticated_root_path %></div>

app/views/groups/show.html.erb
<div class="categories-header">

  <%= render "shared/mobile_menu" %>

  <div>TRANSACTIONS</div>

  <%= link_to authenticated_root_path do %>
    <p> BACK </p>
  <% end %>
</div>

<div class="most-recent">
  <p>Most recent</p>
  <h3>.</h3>
</div>


<div class="cate">
  <div><%= image_tag @group.icon %></div>
  <div class="cate-data-container">
    <p class="cate-name"> <%= @group.name %> </p>
    <p class="cate-time"> <%= @group.created_at.strftime("%d %b %Y") %> </p>
  </div>
  <div> <p class="cate-amount"> $<%= @group.expenses.sum(:amount) %> </p></div>
</div>



<div class="transaction-container">
  <% if @group.expenses.empty? %>
    <p style="color: green; font-size: 20px; text-align: center;">No Transactions Available</p>
  <% else %>
    <% @group.expenses.order(created_at: :desc).each do |expense| %>
      <% if current_user.id == expense.author_id %>
        <div class="cate">
          <div class="cate-data-container">
            <p class="cate-name"> <%= expense.name %> </p>
            <p class="cate-time"> <%= expense.created_at.strftime("%d %b %Y") %> </p>
          </div>
          <div> <p class="cate-amount"> $<%= expense.amount %> </p></div>
        </div>
      <% end %>
    <% end %>
  <% end %>
</div>

<div class="create-new-category"><%= link_to "Add New Transaction", new_user_expense_path(@group.author) %></div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Budget App</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>

    <%= javascript_importmap_tags %>
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">

  </head>

  <body>
    <%= yield %>
  </body>
</html>

<script>
  function initMenu() {
    const ham = document.querySelector('.ham');
    const menu = document.querySelector('.mobile-nav');

    ham.addEventListener('click', () => {
      menu.classList.toggle('menu--open');
    });

    const closeMenuBtn = document.querySelector('.close-x');
    closeMenuBtn.classList.add("close-menu");

    closeMenuBtn.addEventListener("click", () => {
      menu.classList.toggle('menu--open');
    });
  }

  initMenu();
</script>

app/views/shared/_mobile_menu.html.erb
<div class="mobile-menu">
  <%= image_tag("hamburger.png", alt: "Menu", class: "ham") %>
  <nav class="mobile-nav">
    <% if current_user %>
      <ul class="mobile-nav-ul">

        <li class="close-x">&#10006;</li>

        <li class="mobile-nav-name">
          <i class="material-icons">account_circle</i>
          <p class="current-user-name"><%= current_user.name %><?p>
        </li>

        <li class="mobile-nav-li-settings">
          <i class="material-icons">settings</i>
          <%= link_to "Edit Account", edit_user_registration_path, class: "edit-settings" %>
        </li>

        <hr class="mobile-nav-li-hr" >

        <li class="mobile-nav-li-logout">
          <i class="material-icons">exit_to_app</i>
          <%= button_to "Sign Out", destroy_user_session_path, class: "logout", method: :delete %>
        </li>

      </ul>
    <% end %>
  </nav>
</div>

app/views/splash/splash.html.erb
<div class="splash-page-container">
  <div>
    <h1 class="splash-page-title">Budget App</h1>
  </div>

  <div class="auth-buttons">
    <%= link_to "Login", new_user_session_path, class: "auth-login-btn" %>
    <%= link_to "Signup", new_user_registration_path %>
  </div>
</div>